#!/bin/bash

# Array of directories to process
directories=(
    "amalfi-coast_processed_8x"
    "aquarium-nyc_processed_8x"
    "art-museum_processed_8x"
    "backward-jogger_processed_8x"
    "basketball-explosion_processed_8x"
    "big-eyed-fluff-ball_processed_8x"
    "big-sur_processed_8x"
    "birds-over-river_processed_8x"
    "cat-on-bed_processed_8x"
    "chair-archaeology_processed_8x"
    "chameleon_processed_8x"
    "chinese-new-year-dragon_processed_8x"
    "closeup-man-in-glasses_processed_8x"
    "closeup-of-womans-eye_processed_8x"
    "cloud-man_processed_8x"
    "dancing-kangaroo_processed_8x"
    "dogs-downtown_processed_8x"
    "flower-blooming_processed_8x"
    "gold-rush_processed_8x"
    "grandma-birthday_processed_8x"
    "happy-cat_processed_8x"
    "italian-pup_processed_8x"
    "lagos_processed_8x"
    "man-on-the-cloud_processed_8x"
    "mitten-astronaut_processed_8x"
    "monster-with-melting-candle_processed_8x"
    "octopus-and-crab_processed_8x"
    "origami-undersea_processed_8x"
    "otter-on-surfboard_processed_8x"
    "paper-airplanes_processed_8x"
    "petri-dish-pandas_processed_8x"
    "photoreal-train_processed_8x"
    "puppy-cloning_processed_8x"
    "robot-video-game_processed_8x"
    "santorini_processed_8x"
    "ships-in-coffee_processed_8x"
    "snow-dogs_processed_8x"
    "stack-of-tvs_processed_8x"
    "suv-in-the-dust_processed_8x"
    "tiny-construction_processed_8x"
    "tokyo-in-the-snow_processed_8x"
    "tokyo-walk_processed_8x"
    "train-window"_processed_8x
    "victoria-crowned-pigeon_processed_8x"
    "vlogger-corgi_processed_8x"
    "wolves_processed_8x"
    "wooly-mammoth_processed_8x"
    "zen-garden-gnome_processed_8x"
)

# Loop through each directory and run the command
for dir in "${directories[@]}"; do
    echo "Processing $dir..."
    python dup.py interpolated_frames/"$dir"
done
